### ISSUE TITLE
Filter out unrelated constraint changes

### ISSUE THREAD

**Issue by asymmetric** [dapphub/klab#381]
In some cases (which?) klab-debug branches on conditionals where the branches look:

- `A and B`
- `not(B)`

`A` is not explored further, which leads me to believe it shouldn't appear in the first branch.

**Comment by asymmetric** [comment]
This is not a bug.

What's happens in these cases is that the `DELTAC` display is not smart enough to filter out only the changes in constraints that are relevant for this specific branch.

Instead, it shows all the constraints that have changed, even when they changed because one of the branches allows K to simplify some other, unrelated constraints.

E.g. if we're branching on `X == 0`, one of the branches will have a concrete value for `X`, which might simplify other constraints involving `X`.

Labeled this as an *enhancement*, because it could be useful if klab wouldn't show unrelated constraint changes.

**Comment by mhhf** [comment]
Notice that as well, but haven't found a way to come up with an algorithm that decides wether displaying `A` is "relevant". - how do we know if A contains new information or just 'rearanged' information? this seems nontrivial
if you have an idea, let me know

**Comment by mhhf** [comment]
I have an idea how to solve this. When we branch on a constraint `A` we open up two possibilities:
`A` and `~A`
sometimes A is as simple as `X =/= 0`.
what happens in the display is that we do the deltaC aproach for BOTH paths and in the `~A` case `X == 0` a lot of things are affected. 
what we could do is: check the length of deltaC of both cases and choose the smaller one (if its segnificantly smaller) and display this as simply `deltaC(A)` and `~ deltaC(A)` instead of the full `deltaC(~A)`

**Comment by asymmetric** [comment]
> (if its segnificantly smaller)

Do we need this check?

I often see branches like `X ==K 0` vs `(X ==K 0) ==K false`, and I would be in favor of showing `X ==K 0` vs `~(X ==K 0)`. Or as another example, seeing `X >= 3` vs `~(X >= 3)`.
